#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE, POLYGON, MOUSE};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET};

enum ACTION {NONE, CLEAR, UNDO, BRING_TO_FRONT, SEND_TO_BACK, PLUS, MINUS};

#endif
